version: '3.2'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5434:1433"